[build]
  publish = "public"
  functions = "netlify/functions"
  command = "pip install -r requirements.txt --target netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
